# Generated by Django 3.1.6 on 2021-02-17 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20210217_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='overview',
        ),
    ]
