# Generated by Django 3.1.6 on 2021-02-17 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_remove_blog_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
