# Generated by Django 3.1.6 on 2021-02-21 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
