# Generated by Django 3.1.6 on 2021-02-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_home_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_image',
            name='image',
            field=models.ImageField(upload_to='home_image'),
        ),
    ]
